### ISSUE TITLE
Unable to run after a clean composer installation

### ISSUE THREAD

**Issue by finwe** [paragonie/argon2-refiner#1]
Followed the readme, installed with composer in an empty directory:

- No custom composer script was created in composer.json, just a single require line with refiner package
- When trying to run `vendor/bin/benchmark`, the script tries to find autoload in `vendor/paragonie/argon2-refiner/vendor/autoload.php` where it apparently isn't.
- Finally I ended up with quickfixing this by running composer install in `vendor/paragonie/argon2-refiner`, but that's no clean solution

**Comment by paragonie-scott** [comment]
This is fixed in `v0.2.1`. I'm also going to improve the README.

**Comment by finwe** [comment]
Excellent! Thanks.
